In [ ]:
1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.



In [5]:
import numpy as np

npy = np.array([1,2,3,4,5,6,7],dtype="int")

print(npy)
print(f"Arrayin boyutu: {npy.ndim}")
print(f"Arrayin eleman sayısı: {npy.size}")

[1 2 3 4 5 6 7]
Arrayin boyutu: 1
Arrayin eleman sayısı: 7


In [ ]:
2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.

İki boyutlu array:
[[1,2,6,7],
[4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
[[8,6,20],[14,3,9]]]



In [6]:
npy2 = np.array([[1,2,6,7],
[4,3,9,5]])

npy3 = np.array([[[7,5,14],[21,8,11]],
[[8,6,20],[14,3,9]]])


print(f'2 boyut için boyut: {npy2.ndim}')
print(f'2 boyut için eleman sayısı: {npy2.size}')
print(f'2 boyut için satır, sutun: {npy2.shape}')


print(f'3 boyut için boyut: {npy3.ndim}')
print(f'3 boyut için eleman sayısı: {npy3.size}')
print(f'3 boyut için satır, sutun: {npy3.shape}')



2 boyut için boyut: 2
2 boyut için eleman sayısı: 8
2 boyut için satır, sutun: (2, 4)
3 boyut için boyut: 3
3 boyut için eleman sayısı: 12
3 boyut için satır, sutun: (2, 2, 3)


In [ ]:
3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.

İki boyutlu arraydaki 2 elemanına ulaşalım.

İki boyutlu arraydaki 7 elemanına ulaşalım.

Üç boyutlu arraydaki 9 elemanına ulaşalım.

Üç boyutlu arraydaki 5 elemanına ulaşalım.



In [19]:
sayi1 = npy2[0,1]
sayi2 = npy2[0,3]
print(sayi1)
print(sayi2)

2
7


In [21]:
sayi3 = npy3[1, 1 ,2]
sayi4 = npy3[0,0,1]

print(sayi3)
print(sayi4)


9
5


In [ ]:
4. Arrayler üzerinde slicing işlemi uygulayalım.

İki boyutlu array:
[[1,2,6,7],
[4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
[[8,6,20],[14,3,9]]]

İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.

İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.

Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.

Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım.



In [29]:
sayi5 = npy2[0, 1:3]
print(sayi5)

sayi6 =npy2[1,1:4]
print(sayi6)

sayi7 =npy3[0,1:]
print(sayi7)

sayi8 =npy3[1,0, 1:3]
print(sayi8)


[2 6]
[3 9 5]
[[21  8 11]]
[ 6 20]


In [ ]:
5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [31]:
x = np.zeros((5,3), dtype=int)
y = np.ones((5,3), dtype=int)

satir_bir = np.concatenate((x, y), axis=0)
sütun_bir = np.concatenate((x, y), axis=1)
print(satir_bir)
print(sütun_bir)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
